# Generated by Django 5.2.14 on 2026-07-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="адрес доставки"
            ),
        ),
    ]
