# Generated by Django 5.2.14 on 2026-06-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='родительская категория')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, verbose_name='слаг')),
                ('description', models.TextField(verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='старая цена')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='вес в граммах')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='изображение')),
                ('storage_type', models.CharField(choices=[('canned', 'Консервы'), ('frozen', 'Заморозка'), ('other', 'Другое')], default='other', max_length=10, verbose_name='тип хранения')),
                ('product_type', models.CharField(choices=[('stew', 'Тушёнка'), ('pate', 'Паштет'), ('fish', 'Рыбные продукты'), ('vegetables', 'Овощные продукты'), ('ready_meal', 'Готовое блюдо'), ('semi_finished', 'Полуфабрикат'), ('meat', 'Мясо'), ('other', 'Другое')], default='other', max_length=20, verbose_name='тип продукта')),
                ('meat_type', models.CharField(blank=True, choices=[('beef', 'Говядина'), ('pork', 'Свинина'), ('chicken', 'Курица'), ('turkey', 'Индейка'), ('lamb', 'Баранина'), ('mixed', 'Смешанное'), ('none', 'Не указано')], default='none', max_length=10, verbose_name='вид мяса')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='рекомендуемый')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наличии'), ('out_of_stock', 'Нет в наличии'), ('on_order', 'Под заказ')], default='in_stock', max_length=15, verbose_name='наличие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('category', 'name'),
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='unique_product_slug_per_category')],
            },
        ),
    ]
