# Generated by Django 5.2.14 on 2026-09-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='значение')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, verbose_name='слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='catalog.attribute', verbose_name='характеристика')),
            ],
            options={
                'verbose_name': 'значение характеристики',
                'verbose_name_plural': 'значения характеристик',
                'ordering': ('attribute', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, upload_to='collections/', verbose_name='изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('categories', models.ManyToManyField(blank=True, related_name='collections', to='catalog.category', verbose_name='категории')),
            ],
            options={
                'verbose_name': 'подборка',
                'verbose_name_plural': 'подборки',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CollectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_rules', to='catalog.attributevalue', verbose_name='значение характеристики')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='catalog.collection', verbose_name='подборка')),
            ],
            options={
                'verbose_name': 'правило подборки',
                'verbose_name_plural': 'правила подборок',
                'ordering': ('attribute_value__attribute', 'attribute_value'),
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='collections', through='catalog.CollectionRule', to='catalog.attributevalue', verbose_name='правила по характеристикам'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, verbose_name='слаг')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='старая цена')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='вес в граммах')),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='объём в миллилитрах')),
                ('units_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='количество единиц')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='изображение')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_new', models.BooleanField(default=False, verbose_name='новинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_assignments', to='catalog.attributevalue', verbose_name='значение характеристики')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_assignments', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'характеристика товара',
                'verbose_name_plural': 'характеристики товара',
                'ordering': ('attribute_value__attribute', 'attribute_value'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalog.ProductAttributeValue', to='catalog.attributevalue', verbose_name='значения характеристик'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'name'), name='unique_attribute_value_name'),
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'slug'), name='unique_attribute_value_slug'),
        ),
        migrations.AddConstraint(
            model_name='collectionrule',
            constraint=models.UniqueConstraint(fields=('collection', 'attribute_value'), name='unique_collection_attribute_value'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_value'), name='unique_product_attribute_value'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_product_slug_per_category'),
        ),
    ]
